import React from "react";

const Javascript = () => {
  return (
    <div
      style={{
        height: "100vh",
        display: "flex",
        alignItems: "center",
      }}
    >
      <div>
        <img
          src="https://www.interviewbit.com/blog/wp-content/uploads/2021/08/javascript.jpg"
          height={200}
          width={200}
          alt=""
        />
      </div>
      <div style={{ display: "flex", flexDirection: "column" }}>
        <span>
          <b>Language:</b>javascript
        </span>
        <br></br>
        <span>
          <b>Description:</b>
          <p
            style={{
              wordSpacing: "5px",
              lineHeight: "2.0",
              margin: "0 50px",
              color: "gray",
            }}
          >
            JavaScript is a dynamic computer programming language. It is
            lightweight and most commonly used as a part of web pages, whose
            implementations allow client-side script to interact with the user
            and make dynamic pages. It is an interpreted programming language
            with object-oriented capabilities. JavaScript was first known as
            LiveScript, but Netscape changed its name to JavaScript, possibly
            because of the excitement being generated by Java. JavaScript made
            its first appearance in Netscape 2.0 in 1995 with the name
            LiveScript. The general-purpose core of the language has been
            embedded in Netscape, Internet Explorer, and other web browsers
          </p>
        </span>
      </div>
    </div>
  );
};

export default Javascript;
